services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app:cached
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://postgres:5442983-8@db:5432/patients
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/.env:/usr/src/app/.env
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5442983-8
      POSTGRES_DB: patients
    ports:
      - "5432:5432"
